// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6c6CJCLj0DluKeT2ffVmVczsyoILYGpQ',
    appId: '1:663205153036:web:a3f7592d46a4006041a129',
    messagingSenderId: '663205153036',
    projectId: 'transignition-app',
    authDomain: 'transignition-app.firebaseapp.com',
    storageBucket: 'transignition-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgnUtcjUj67o0MttozPmd982z5jTRkAEY',
    appId: '1:663205153036:android:ea8aafe494e0e7e741a129',
    messagingSenderId: '663205153036',
    projectId: 'transignition-app',
    storageBucket: 'transignition-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDont6XICqg1bOXlUyqUuUZv5WgguGTX9M',
    appId: '1:663205153036:ios:648a3eb1bdf26dde41a129',
    messagingSenderId: '663205153036',
    projectId: 'transignition-app',
    storageBucket: 'transignition-app.firebasestorage.app',
    iosBundleId: 'com.example.transignition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDont6XICqg1bOXlUyqUuUZv5WgguGTX9M',
    appId: '1:663205153036:ios:648a3eb1bdf26dde41a129',
    messagingSenderId: '663205153036',
    projectId: 'transignition-app',
    storageBucket: 'transignition-app.firebasestorage.app',
    iosBundleId: 'com.example.transignition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6c6CJCLj0DluKeT2ffVmVczsyoILYGpQ',
    appId: '1:663205153036:web:47915d7def9c1a9141a129',
    messagingSenderId: '663205153036',
    projectId: 'transignition-app',
    authDomain: 'transignition-app.firebaseapp.com',
    storageBucket: 'transignition-app.firebasestorage.app',
  );
}
