import 'package:transignition/main.dart';

class TranslateService {
  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      // General
      'Yes': 'Yes',
      'No': 'No',
      'Cancel': 'Cancel',
      'Later': 'Later',
      'Restart Required': 'Restart Required',
      'The app needs to be restarted for the language changes to take effect. Do you want to restart now?': 'The app needs to be restarted for the language changes to take effect. Do you want to restart now?',
      'Restart Now': 'Restart Now',
      'An error occurred': 'An error occurred',
      'Logout failed: ': 'Logout failed: ',
      'Password must be at least 6 characters': 'Password must be at least 6 characters',
      'Please enter your ': 'Please enter your ',

      // LoginPage
      'Welcome Back': 'Welcome Back',
      'Enter your details to proceed': 'Enter your details to proceed',
      'Email Address': 'Email Address',
      'Password': 'Password',
      'Forgot Password?': 'Forgot Password?',
      'Sign In': 'Sign In',
      'Or sign in with': 'Or sign in with',
      'Sign in with Google': 'Sign in with Google',
      'Don\'t have an account? ': 'Don\'t have an account? ',
      'Sign Up': 'Sign Up',
      'Login failed': 'Login failed',
      
      // SignupPage
      'Create Account': 'Create Account',
      'Register below to start': 'Register below to start',
      'Username': 'Username',
      'Confirm Password': 'Confirm Password',
      'Passwords do not match': 'Passwords do not match',
      'Already have an account? ': 'Already have an account? ',
      'Registration failed': 'Registration failed',

      // ForgotPassword
      'Reset Password': 'Reset Password',
      'Enter your email to receive a password reset link': 'Enter your email to receive a password reset link',
      'Send Reset Link': 'Send Reset Link',
      'Password reset email sent!': 'Password reset email sent!',
      'Failed to send reset email': 'Failed to send reset email',

      // Dashboard
      'Unlock your motorcycle first!': 'Unlock your motorcycle first!',
      'Turn off the engine to lock the motorcycle.': 'Turn off the engine to lock the motorcycle.',
      'Face Recognized. Unlocked & Engine On.': 'Face Recognized. Unlocked & Engine On.',
      'Motorcycle structure Locked.': 'Motorcycle structure Locked.',
      'Good Morning': 'Good Morning',
      'Good Afternoon': 'Good Afternoon',
      'Good Evening': 'Good Evening',
      'Good Night': 'Good Night',
      'Connect to ESP32': 'Connect to ESP32',
      'Enter the SIM card number or Device ID to establish a connection with the motorcycle\'s module.': 'Enter the SIM card number or Device ID to establish a connection with the motorcycle\'s module.',
      'SIM Number / ESP32 ID': 'SIM Number / ESP32 ID',
      'Connected to TransIgnition GSM module': 'Connected to TransIgnition GSM module',
      'Connect Device': 'Connect Device',
      'START': 'START',
      'ENGINE ON': 'ENGINE ON',
      'Status': 'Status',
      'Connected to ESP32': 'Connected to ESP32',
      'Tap to connect': 'Tap to connect',
      'Locked': 'Locked',
      'Unlocked': 'Unlocked',
      'Evaluation': 'Evaluation',

      // Face Scan
      'Face scanner failed: Please ensure you grant camera permissions.': 'Face scanner failed: Please ensure you grant camera permissions.',
      'Face scanning failed: Please ensure you grant camera permission.': 'Face scanning failed: Please ensure you grant camera permission.',
      'Face Authentication': 'Face Authentication',
      'Identity Confirmed': 'Identity Confirmed',
      'Position your face in the frame': 'Position your face in the frame',
      'Position your face within the frame': 'Position your face within the frame',
      'Unlocking TransIgnition...': 'Unlocking TransIgnition...',
      'Opening TransIgnition...': 'Opening TransIgnition...',
      'Scanning for registered face...': 'Scanning for registered face...',
      'Scanning registered face...': 'Scanning registered face...',
      'Initializing camera...': 'Initializing camera...',
      'Preparing camera...': 'Preparing camera...',

      // Fisherface Stats
      'Fisherface Evaluation': 'Fisherface Evaluation',
      'Algorithm Performance': 'Algorithm Performance',
      'Accuracy': 'Accuracy',
      'Error Rate': 'Error Rate',
      'Avg. Time': 'Avg. Time',
      'Avg Time': 'Avg Time',
      'Threshold': 'Threshold',
      'Confusion Matrix Details': 'Confusion Matrix Details',
      'True Positives (TP)': 'True Positives (TP)',
      'True Negatives (TN)': 'True Negatives (TN)',
      'False Positives (FP)': 'False Positives (FP)',
      'False Negatives (FN)': 'False Negatives (FN)',
      'Metric Scores': 'Metric Scores',
      'Precision': 'Precision',
      'Recall': 'Recall',
      'F1-Score': 'F1-Score',

      // Settings Account
      'Profile photo updated!': 'Profile photo updated!',
      'Failed to upload photo: ': 'Failed to upload photo: ',
      'Change Profile Photo': 'Change Profile Photo',
      'Choose from Gallery': 'Choose from Gallery',
      'Take a Photo': 'Take a Photo',
      'Take Photo': 'Take Photo',
      'A verification email has been sent. Please verify your new email.': 'A verification email has been sent. Please verify your new email.',
      'Profile updated successfully': 'Profile updated successfully',
      'Settings & Profile': 'Settings & Profile',
      'Tap to change photo': 'Tap to change photo',
      'Edit Profile': 'Edit Profile',
      'New Password (Optional)': 'New Password (Optional)',
      'Save Changes': 'Save Changes',
      'Face Registration': 'Face Registration',
      'Register Face Data': 'Register Face Data',
      'Add or update your face data': 'Add or update your face data',
      'Appearance': 'Appearance',
      'System Default': 'System Default',
      'Light Mode': 'Light Mode',
      'Dark Mode': 'Dark Mode',
      'Language / Bahasa': 'Language / Bahasa',
      'Language': 'Language',
      'Logout Account': 'Logout Account',
      'Sign Out': 'Sign Out',
      'Logout': 'Logout',
      'Are you sure you want to log out of your account?': 'Are you sure you want to log out of your account?',
      'Are you sure you want to sign out of your account?': 'Are you sure you want to sign out of your account?',

      // Face Registration
      'Please look straight...': 'Please look straight...',
      'Look straight...': 'Look straight...',
      'Slowly turn head to the left...': 'Slowly turn head to the left...',
      'Turn left slowly...': 'Turn left slowly...',
      'Slowly turn head to the right...': 'Slowly turn head to the right...',
      'Turn right slowly...': 'Turn right slowly...',
      'Slightly tilt your head up...': 'Slightly tilt your head up...',
      'Look up slightly...': 'Look up slightly...',
      'Slightly tilt your head down...': 'Slightly tilt your head down...',
      'Look down slightly...': 'Look down slightly...',
      'Face registration failed: Please ensure you grant camera permissions.': 'Face registration failed: Please ensure you grant camera permissions.',
      'Face registration failed: Please ensure you grant camera permission.': 'Face registration failed: Please ensure you grant camera permission.',
      'Registration Complete': 'Registration Complete',
      'Scanning face... ': 'Scanning face... ',
      'Scanning face...': 'Scanning face...',
      'Face data saved successfully!': 'Face data saved successfully!',
      'Face data successfully saved!': 'Face data successfully saved!',
    },
    'id': {
      // General
      'Yes': 'Ya',
      'No': 'Tidak',
      'Cancel': 'Batal',
      'Later': 'Nanti',
      'Restart Required': 'Perlu Memulai Ulang',
      'The app needs to be restarted for the language changes to take effect. Do you want to restart now?': 'Aplikasi perlu dimulai ulang agar perubahan bahasa diterapkan. Apakah Anda ingin memulai ulang sekarang?',
      'Restart Now': 'Mulai Ulang Sekarang',
      'An error occurred': 'Terjadi kesalahan',
      'Logout failed: ': 'Gagal keluar: ',
      'Password must be at least 6 characters': 'Kata sandi harus minimal 6 karakter',
      'Please enter your ': 'Harap masukkan ',

      // LoginPage
      'Welcome Back': 'Selamat Datang Kembali',
      'Enter your details to proceed': 'Masukkan detail Anda untuk melanjutkan',
      'Email Address': 'Alamat Email',
      'Password': 'Kata Sandi',
      'Forgot Password?': 'Lupa Kata Sandi?',
      'Sign In': 'Masuk',
      'Or sign in with': 'Atau masuk dengan',
      'Sign in with Google': 'Masuk dengan Google',
      'Don\'t have an account? ': 'Belum punya akun? ',
      'Sign Up': 'Daftar',
      'Login failed': 'Masuk gagal',
      
      // SignupPage
      'Create Account': 'Buat Akun',
      'Register below to start': 'Daftar di bawah untuk memulai',
      'Username': 'Nama Pengguna',
      'Confirm Password': 'Konfirmasi Kata Sandi',
      'Passwords do not match': 'Kata sandi tidak cocok',
      'Already have an account? ': 'Sudah punya akun? ',
      'Registration failed': 'Pendaftaran gagal',

      // ForgotPassword
      'Reset Password': 'Setel Ulang Kata Sandi',
      'Enter your email to receive a password reset link': 'Masukkan email Anda untuk menerima tautan setel ulang kata sandi',
      'Send Reset Link': 'Kirim Tautan',
      'Password reset email sent!': 'Email setel ulang kata sandi terkirim!',
      'Failed to send reset email': 'Gagal mengirim email setel ulang',

      // Dashboard
      'Unlock your motorcycle first!': 'Buka kunci motor Anda terlebih dahulu!',
      'Turn off the engine to lock the motorcycle.': 'Matikan mesin untuk mengunci motor.',
      'Face Recognized. Unlocked & Engine On.': 'Wajah Dikenali. Kunci Terbuka & Mesin Nyala.',
      'Motorcycle structure Locked.': 'Motor Terkunci.',
      'Good Morning': 'Selamat Pagi',
      'Good Afternoon': 'Selamat Siang',
      'Good Evening': 'Selamat Sore',
      'Good Night': 'Selamat Malam',
      'Connect to ESP32': 'Hubungkan ke ESP32',
      'Enter the SIM card number or Device ID to establish a connection with the motorcycle\'s module.': 'Masukkan nomor kartu SIM atau ID Perangkat untuk menghubungkan modul motor.',
      'SIM Number / ESP32 ID': 'Nomor SIM / ID ESP32',
      'Connected to TransIgnition GSM module': 'Terhubung ke modul GSM TransIgnition',
      'Connect Device': 'Hubungkan Perangkat',
      'START': 'NYALAKAN',
      'ENGINE ON': 'MESIN NYALA',
      'Status': 'Status',
      'Connected to ESP32': 'Terhubung ke ESP32',
      'Tap to connect': 'Ketuk untuk menghubungkan',
      'Locked': 'Terkunci',
      'Unlocked': 'Terbuka',
      'Evaluation': 'Evaluasi',

      // Face Scan
      'Face scanner failed: Please ensure you grant camera permissions.': 'Pemindai wajah gagal: Harap pastikan Anda memberikan izin kamera.',
      'Face scanning failed: Please ensure you grant camera permission.': 'Pemindai wajah gagal: Harap pastikan Anda memberikan izin kamera.',
      'Face Authentication': 'Autentikasi Wajah',
      'Identity Confirmed': 'Identitas Dikonfirmasi',
      'Position your face in the frame': 'Posisikan wajah Anda di dalam bingkai',
      'Position your face within the frame': 'Posisikan wajah Anda di dalam bingkai',
      'Unlocking TransIgnition...': 'Membuka TransIgnition...',
      'Opening TransIgnition...': 'Membuka TransIgnition...',
      'Scanning for registered face...': 'Memindai wajah terdaftar...',
      'Scanning registered face...': 'Memindai wajah terdaftar...',
      'Initializing camera...': 'Menyiapkan kamera...',
      'Preparing camera...': 'Menyiapkan kamera...',

      // Fisherface Stats
      'Fisherface Evaluation': 'Evaluasi Fisherface',
      'Algorithm Performance': 'Performa Algoritma',
      'Accuracy': 'Akurasi',
      'Error Rate': 'Tingkat Kesalahan',
      'Avg. Time': 'Waktu Rata-rata',
      'Avg Time': 'Waktu Rata-rata',
      'Threshold': 'Batas Algoritma',
      'Confusion Matrix Details': 'Detail Confusion Matrix',
      'True Positives (TP)': 'Positif Benar (TP)',
      'True Negatives (TN)': 'Negatif Benar (TN)',
      'False Positives (FP)': 'Positif Salah (FP)',
      'False Negatives (FN)': 'Negatif Salah (FN)',
      'Metric Scores': 'Skor Metrik',
      'Precision': 'Presisi',
      'Recall': 'Recall',
      'F1-Score': 'Skor F1',

      // Settings Account
      'Profile photo updated!': 'Foto profil diperbarui!',
      'Failed to upload photo: ': 'Gagal mengunggah foto: ',
      'Change Profile Photo': 'Ubah Foto Profil',
      'Choose from Gallery': 'Pilih dari Galeri',
      'Take a Photo': 'Ambil Foto',
      'Take Photo': 'Ambil Foto',
      'A verification email has been sent. Please verify your new email.': 'Email verifikasi telah dikirim. Harap verifikasi email baru Anda.',
      'Profile updated successfully': 'Profil berhasil diperbarui',
      'Settings & Profile': 'Pengaturan & Profil',
      'Tap to change photo': 'Ketuk untuk mengubah foto',
      'Edit Profile': 'Edit Profil',
      'New Password (Optional)': 'Kata Sandi Baru (Opsional)',
      'Save Changes': 'Simpan Perubahan',
      'Face Registration': 'Pendaftaran Wajah',
      'Register Face Data': 'Daftarkan Data Wajah',
      'Add or update your face data': 'Tambahkan atau perbarui data wajah Anda',
      'Appearance': 'Tampilan',
      'System Default': 'Bawaan Sistem',
      'Light Mode': 'Mode Terang',
      'Dark Mode': 'Mode Gelap',
      'Language / Bahasa': 'Language / Bahasa',
      'Language': 'Bahasa',
      'Logout Account': 'Keluar Akun',
      'Sign Out': 'Keluar Akun',
      'Logout': 'Keluar',
      'Are you sure you want to log out of your account?': 'Apakah Anda yakin ingin keluar dari akun Anda?',
      'Are you sure you want to sign out of your account?': 'Apakah Anda yakin ingin keluar dari akun Anda?',

      // Face Registration
      'Please look straight...': 'Luruskan wajah...',
      'Look straight...': 'Luruskan wajah...',
      'Slowly turn head to the left...': 'Tengok kiri secara perlahan...',
      'Turn left slowly...': 'Tengok kiri secara perlahan...',
      'Slowly turn head to the right...': 'Tengok kanan secara perlahan...',
      'Turn right slowly...': 'Tengok kanan secara perlahan...',
      'Slightly tilt your head up...': 'Dongak ke atas sedikit...',
      'Look up slightly...': 'Dongak ke atas sedikit...',
      'Slightly tilt your head down...': 'Tunduk ke bawah sedikit...',
      'Look down slightly...': 'Tunduk ke bawah sedikit...',
      'Face registration failed: Please ensure you grant camera permissions.': 'Pendaftaran wajah gagal: Harap pastikan Anda memberikan izin kamera.',
      'Face registration failed: Please ensure you grant camera permission.': 'Pendaftaran wajah gagal: Harap pastikan Anda memberikan izin kamera.',
      'Registration Complete': 'Pendaftaran Selesai',
      'Scanning face... ': 'Memindai wajah... ',
      'Scanning face...': 'Memindai wajah... ',
      'Face data saved successfully!': 'Data wajah berhasil disimpan!',
      'Face data successfully saved!': 'Data wajah berhasil disimpan!',
    },
  };

  static String tr(String key) {
    String currentLang = languageNotifier.value;
    // Default to 'en' if not found
    if (!_localizedStrings.containsKey(currentLang)) {
      currentLang = 'en';
    }
    return _localizedStrings[currentLang]?[key] ?? key;
  }
}
